
### Traer Tareas
GET http://localhost:3000/api/tasks

### Crear Tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title":"nuevo titulo",
    "description":"nueva descripcion",
    "poster":"www.url.com"
}

### ELIMINAR
DELETE http://localhost:3000/api/tasks/1


