
### Traer Tareas
GET http://localhost:3000/api/tasks

### Crear Tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "22",
    "description":"nueva descripcion",
    "poster":"www.url.com"
}

### Modificar Tarea
PUT http://localhost:3000/api/tasks/2
Content-Type: application/json

{
    "title":"Primer tarea"
}

### ELIMINAR
DELETE http://localhost:3000/api/tasks/3


