
### Traer Tareas
GET http://localhost:3000/api/tasks

### Crear Tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Cuarto Posteo",
    "description":"Cuarta descripcion",
    "poster": "https://img.freepik.com/vector-gratis/concepto-videoconferencia-landing-page_52683-11841.jpg"
}

### Modificar Tarea
PUT http://localhost:3000/api/tasks/
Content-Type: application/json

{
    "title":"Primer tarea"
}

### ELIMINAR
DELETE http://localhost:3000/api/tasks/


